services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot-path:/var/www/html
    depends_on:
      - frontend_portfolio
      - backend_manager
      - frontend_manager
      - frontend-user_flowers
      - frontend-admin_flowers
      - backend_flowers
      - backend_portfolio
  certbot:
    image: certbot/certbot
    container_name: certbot_portfolio
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot-path:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db_flowers:
    image: postgres:18.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_flowers:/var/lib/postgresql
  backend_flowers:
    restart: always
    build: ./flowers/backend
    depends_on:
      - db_flowers
    environment:
      DB_URL: 'jdbc:postgresql://db_flowers:5432/${POSTGRES_DB}'
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      IMAGE_PATH: /app/images/img
      IMAGE_MAIN_PATH: /app/images/mainImg
    volumes:
      - flowers_images:/app/images
  frontend-admin_flowers:
    restart: always
    build: ./flowers/frontend/admin-flowers
  frontend-user_flowers:
    restart: always
    build: ./flowers/frontend/front-flowers
  backend_portfolio:
    restart: always
    build: ./portfolio/backend
    environment:
      token: ${token}
      chat_id: ${chat_id}
  frontend_portfolio:
    restart: always
    build: ./portfolio/frontend
  db_manager:
    image: postgres:18.2
    container_name: db_manager
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER_MANAGER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_MANAGER}
      - POSTGRES_DB=${POSTGRES_DB_MANAGER}
    volumes:
      - pg_manager:/var/lib/postgresql
  backend_manager:
    restart: always
    build: ./task-manager/backend
    depends_on:
      - db_manager
    environment:
      DB_URL: ${POSTGRES_URL_MANAGER}
      DB_USERNAME: ${POSTGRES_USER_MANAGER}
      DB_PASSWORD: ${POSTGRES_PASSWORD_MANAGER}
      IMAGE_PATH: ${IMAGE_PATH_MANAGER}
    volumes:
      - profile:/app/images
  frontend_manager:
    restart: always
    build: ./task-manager/frontend

volumes:
  pg_flowers:
  flowers_images:
  pg_manager:
  profile:
  certbot-etc:
  certbot-var:
  webroot-path:
