server {
    listen 80;
    server_name portfollio-gab.ru www.portfollio-gab.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        proxy_pass http://frontend_portfolio:80;
        proxy_set_header HOST $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /portfolio-api/ {
        proxy_pass http://backend_portfolio:8080/;
        proxy_set_header HOST $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /task-manager/ {
        proxy_pass http://frontend_manager:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://backend_manager:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /flowers/ {
        proxy_pass http://frontend-user_flowers:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /flowers-admin/ {
        proxy_pass http://frontend-admin_flowers:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api-flowers/ {
        client_max_body_size 50M;
        proxy_pass http://backend_flowers:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}