server{
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location = /policy {
    rewrite ^/policy$ /doc/policy.pdf break;
  }
  location = /agreement {
    rewrite ^/agreement$ /doc/agreement.pdf break;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}